---
- name: 'Docker image pull from docker repository'
  hosts: localhost
  tasks:
  - name: 'PULL AN IMAGE'
    docker_image:
      name: "{{ item }}"
      source: pull
    loop:
    - httpd
    - centos
    - redis
    - alpine
